name: Test Web

on:
  push:
    paths:
      - '**'
      - '!apps/**'
      - 'apps/web/**'
      - '!.github/**'
      - '.github/workflows/web_coverage_test.yml'
  pull_request:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ~/.cache/Cypress
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress
        run: pnpm --filter=web cypress:install

      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install: false
          start: pnpm start
          wait-on: 'http://localhost:3000'
          command: npx cypress run
          working-directory: apps/web

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: apps/web/cypress/videos
